FROM python:3.12-slim

WORKDIR /app

COPY *.py ./
COPY entrypoint.sh ./

RUN chmod +x entrypoint.sh

ENV NICKNAME=A
ENV TOKEN_DELAY=0.1
ENV DATA_DELAY=0.1
ENV TOKEN_TIMEOUT=5.0
ENV MIN_TOKEN_INTERVAL=0.5
ENV ERROR_PROBABILITY=0.0

ENTRYPOINT ["./entrypoint.sh"]
